### ISSUE TITLE
Add styling for favorite listings on favorites.html page to list cards horizontally in rows of 3 rather than in a singular vertical column

### ISSUE THREAD

**Issue by ryanpjhickey** [ryanpjhickey/Paws-to-Home#22]
Currently, the favorites listed on the favorites.html page show in a line straight down. Ideally, it should be styled similarly to the front page when searching for results.

How it currently looks:
![image](https://user-images.githubusercontent.com/108383347/214756120-8ed45206-3914-44f1-8e52-1b56196cc57c.png)

How it should look:
![image](https://user-images.githubusercontent.com/108383347/214756053-256a90f6-f682-4209-8877-8b39c33cbfe3.png)

**Comment by Aeilxs** [comment]
i can do it

**Comment by ryanpjhickey** [comment]
This has already been fixed @Aeilxs. Thank you for offering! I have a few other requests available if you're interested in those.

**Comment by Aeilxs** [comment]
sure why not !
